kind: pipeline
type: docker
name: default

steps:
- name: docker-image
  image: plugins/docker
  commands:
  - pwd
  - ls
  - cd ~
  - pwd
  #- docker build -t my_first_image .
  - echo image created
