kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/ecr
    settings:
      dry_run: true
      access_key:
        from_secret: aws_access_key_id
      secret_key:
        from_secret: aws_secret_access_key
      repo: droneci_testing
      tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
