kind: pipeline
type: docker
name: default

steps:
- name: docker-image
  image: ubuntu
  commands:
  - ls
  - sudo docker build -t my_first_image .
  #- systemctl start docker
  #- systemctl status docker
  - echo image created
