# ---
# kind: pipeline
# type: docker
# name: default

# steps:
# - name: hello
#   image: busybox
#   commands:
#   - echo Prebuild image

# trigger:
#   branch:
#   - main
kind: pipeline
type: docker
name: default

steps:
- name: docker-image
  commands:
  - docker build -t my_first_image .
  - echo image created
