kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/ecr
    settings:
      dry_run: true
      access_key: AKIAYZMOHPKURF2GC636
      secret_key: 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
      repo: droneci_testing
      registry: 604278061737.dkr.ecr.ap-south-1.amazonaws.com
      tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
