kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: plugins/docker
    settings:
      dry_run: true
      repo: example/imagename
      tags:
      - latest
      - ${DRONE_COMMIT_SHA:0:8}
